version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: react_tsx_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"

volumes:
  node_modules:
